url: "https://controlledchaos.github.io"
is_user_page: true
is_project_page: false
remote_theme: theme-ccdzen

title: Controlled Chaos
description: Custom website design and build. Free products to build your own.
image: /assets/img/default-cover.jpg
repository: ControlledChaos/controlledchaos.github.io

# An empty path string means all files in the project.
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      image: /assets/img/default-cover.jpg
      layout: "post"
      permalink: /posts/:title/
      toc: true
  - scope:
      path:
      type: "pages"
    values:
      layout: "page"
      image: /assets/img/default-cover.jpg

user_image: /assets/img/site-icon.png
header_icon: favicon

nav:
  - name: Posts
    url: /posts
  - name: Categories
    url: /category/

links:
  - name: All blog posts
    url: /posts
    thumbnail: /assets/img/blog-post-icon.png
  - name: Browse by category
    url: /category/
    thumbnail: /assets/img/category-icon.png

related_by: "tags or categories"

paginate: 2
paginate_path: "/posts/page:num"

tag_page_layout: tags
tag_page_dir: tags

category_path: category
category_layout: category_layout.html

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-gist
  - jekyll-toc
  - jemoji
